version: '3.8'

services:
  customer_service:
    container_name: customer_service
    build: ./customer_service
    ports:
      - "3000:3000"

  post_service:
    container_name: post_service
    build: ./post_service
    ports:
      - "4000:4000"

  review_service:
    container_name: review_service
    build: ./review_service
    ports:
      - "2000:2000"
 
  api:
    build: ./api_gateway
    depends_on:
      - "customer_service"
      - "post_service"
      - "review_service"
      - "redisdb"

  redisdb:
    image: redis
    ports:
      - "6379:6379"